//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HierarchyInEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ContactEmployee : Employee
    {
        [Column(Order = 5)]
        public Nullable<int> HourlyPay { get; set; }

        [Column(Order = 6)]
        public Nullable<int> HoursWorked { get; set; }
    }
}
